import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { app } from "./layout.css";

const pretendard = localFont({
  src: "./fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
  variable: "--font-pretendard",
});

const notoSansMonoCjkKr = localFont({
  src: "./fonts/NotoSansMonoCJKkr-VF.subset.woff2",
  display: "swap",
  weight: "400 700",
  preload: false,
  variable: "--font-noto-sans-mono-cjk-kr",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${pretendard.variable} ${notoSansMonoCjkKr.variable}`}>
      <body>
        <div className={app}>{children}</div>
      </body>
    </html>
  );
}
